on:
  push:
    branches:
      - feature**

permissions:
  pull-requests: write

jobs:
  open-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v4
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      - name: Open PR
        run: gh pr create --base main --head ${{ github.ref }} --title "Open PR from ${{ steps.extract_branch.outputs.branch }}" --body "This is an open PR from ${{ steps.extract_branch.outputs.branch }} branch."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}